import React from 'react';
import { Modal, View, Text, ScrollView, TouchableOpacity } from 'react-native';

export default function PolicyModal({ visible, onClose, onAccept }) {
  return (
    <Modal visible={visible} transparent animationType="slide">
      <View style={{ flex: 1, backgroundColor: 'rgba(0,0,0,0.4)', justifyContent: 'flex-end' }}>
        <View style={{ maxHeight: '80%', backgroundColor: '#fff', borderTopLeftRadius: 20, borderTopRightRadius: 20, padding: 16 }}>
          <View style={{ alignItems: 'center', marginBottom: 8 }}>
            <View style={{ width: 48, height: 4, backgroundColor: '#ddd', borderRadius: 2 }} />
          </View>
          <Text style={{ fontSize: 20, fontWeight: '700', marginBottom: 8 }}>Privacy & User Agreements</Text>
          <ScrollView style={{ marginBottom: 16 }}>
            <Text style={{ lineHeight: 20 }}>
              {/* Replace with your actual policy text */}
              1. We collect your email for account creation and authentication.{"\n"}
              2. We store layout images you upload to improve your experience.{"\n"}
              3. AI suggestions are generated by third‑party models; do not upload sensitive info.{"\n"}
              4. You can request deletion of your data anytime via Profile → Delete Account.{"\n"}
              5. Read the full Privacy Policy at example.com/privacy and Terms at example.com/terms.
            </Text>
          </ScrollView>
          <View style={{ flexDirection: 'row', gap: 12 }}>
            <TouchableOpacity onPress={onClose} style={{ flex: 1, padding: 12, borderWidth: 1, borderColor: '#ddd', borderRadius: 12, alignItems: 'center' }}>
              <Text style={{ fontWeight: '600' }}>Close</Text>
            </TouchableOpacity>
            <TouchableOpacity onPress={() => { onAccept?.(); onClose?.(); }} style={{ flex: 1, padding: 12, backgroundColor: '#111827', borderRadius: 12, alignItems: 'center' }}>
              <Text style={{ color: '#fff', fontWeight: '700' }}>I Agree</Text>
            </TouchableOpacity>
          </View>
        </View>
      </View>
    </Modal>
  );
}
